server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  instance:
    hostname: ${eureka_host}
    port: ${eureka_port}
    prefer-ip-address: true

integration:
  base-url: https://161.35.252.68/ # https://restcountries.com/
  url:
    country: /v3.1/name/%s