server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:9001/eureka/
  instance:
    hostname: ${host}
    prefer-ip-address: true

integration:
  base-url: https://161.35.252.68/
  url:
    country: /v3.1/name/%s