server:
  port: 9001

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: ${eureka_host}
    prefer-ip-address: true
  server:
    renewal-percent-threshold: 0.25