server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  instance:
    hostname: ${eureka_host}
    port: ${eureka_port}
    prefer-ip-address: true

integration:
  base-url: https://jsonplaceholder.typicode.com/
  url:
    posts: /users/%d/posts
    todos: /users/%d/todos
    albums: /users/%d/albums