server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9001/eureka/
  instance:
    hostname: ${host}

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: forum-data-app
        uri: lb://forum-data-app
        predicates:
        - Path=/forum-data/api/**
        filters:
        - RewritePath=/(?<path>.*), /$\{path}
      - id: person-data-app
        uri: lb://person-data-app
        predicates:
          - Path=/person-data/api/**
        filters:
          - RewritePath=/(?<path>.*), /$\{path}