server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  instance:
    hostname: ${eureka_host}
    port: ${eureka_port}
    prefer-ip-address: true

integration:
  base-url: https://randomuser.me/
  url:
    person: /api/
  local:
    country-app: lb://country-data-app
    url:
      country: /country-data/api/v1/country/%s

