server:
  port: 9002

spring:
  profiles:
    active: native
  application:
    name: config-service
  cloud:
    config:
      server:
        native:
          searchLocations: "[classpath:/, classpath:/configs, classpath:/configs/{application}, classpath:/configs/{application}/{profile}]"